### ISSUE TITLE
genesis-data.link

### ISSUE THREAD

**Issue by Kwaskoff** [cyberway/cyberway.launch#4]
after launched ./start_light.sh

++ curl --silent https://raw.githubusercontent.com/cyberway/cyberway.launch/master/genesis-data.link
+ local 'genesis_data_url=404: Not Found'

Why?

**Comment by Vik-BC** [comment]
Cause genesis data will be generated only after taking hard fork today @ 12PM

**Comment by cryptomental** [comment]
Hi @vikxx , @Kwaskoff . I see the data are available. Is https://golos.io a frontend to cyberway chain and https://golos.id to golos classic? And does rudex support still golos classic? What is the plan for exchanges support?

**Comment by bitphage** [comment]
@cryptomental rudex will stick to golos classic chain.

**Comment by cryptomental** [comment]
@bitfag all right, thank you!

**Comment by afalaleev** [comment]
Link returns `https://download.cyberway.io/genesis.dat`
